### ISSUE TITLE
Mismatched function names (empty!, reset!)

### ISSUE THREAD

**Issue by ffreyer** [crstnbr/MonteCarloObservable.jl#38]
`Observable`s implement `reset!` to clear data, while `LightObservable`s forward `empty!` from BinningAnalysis for the same purpose. These should have the same name.

**Comment by ffreyer** [comment]
Do we want `empty!`, `reset!` or both?

**Comment by crstnbr** [comment]
I'd say let's go with `empty!` and deprecate `reset!` for observables (`@deprecated`).
